# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='released_at',
            field=models.DateField(blank=True),
        ),
    ]
